---
language: ruby

cache: bundler
sudo: false

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5

script: bundle exec rake test
bundler_args: --without development
before_install: rm Gemfile.lock || true

env:
  - PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES="yes"
  - PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES="yes" FUTURE_PARSER="yes"
  - PUPPET_VERSION="~> 3.8.1" STRICT_VARIABLES="yes"
  - PUPPET_VERSION="~> 3.8.1" STRICT_VARIABLES="yes" FUTURE_PARSER="yes"
  - PUPPET_VERSION="~> 4.0.0" STRICT_VARIABLES="yes"
  - PUPPET_VERSION="~> 4.1.0" STRICT_VARIABLES="yes"
  - PUPPET_VERSION="~> 4.2.0" STRICT_VARIABLES="yes"

matrix:
  allow_failures:
    - env: PUPPET_VERSION="~> 4.0.0" STRICT_VARIABLES="yes"
    - env: PUPPET_VERSION="~> 4.1.0" STRICT_VARIABLES="yes"
    - env: PUPPET_VERSION="~> 4.2.0" STRICT_VARIABLES="yes"
